# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{algorithms-aunderwo}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kanwei Li", "Anthony Underwood"]
  s.date = %q{2010-07-29}
  s.description = %q{A modfication of the algorithms gem to include the latest String function}
  s.email = %q{algorithms@ants.otherinbox.co, kanwei@gmail.com}
  s.extensions = ["ext/algorithms/string/extconf.rb", "ext/containers/splaytree_map/extconf.rb", "ext/containers/bst/extconf.rb", "ext/containers/rbtree_map/extconf.rb", "ext/containers/deque/extconf.rb"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "algorithms-aunderwo.gemspec",
     "algorithms.gemspec",
     "benchmarks/deque.rb",
     "benchmarks/sorts.rb",
     "benchmarks/treemaps.rb",
     "ext/algorithms/string/extconf.rb",
     "ext/algorithms/string/string.c",
     "ext/containers/bst/bst.c",
     "ext/containers/bst/extconf.rb",
     "ext/containers/deque/deque.c",
     "ext/containers/deque/extconf.rb",
     "ext/containers/rbtree_map/extconf.rb",
     "ext/containers/rbtree_map/rbtree.c",
     "ext/containers/splaytree_map/extconf.rb",
     "ext/containers/splaytree_map/splaytree.c",
     "lib/algorithms.rb",
     "lib/algorithms/search.rb",
     "lib/algorithms/sort.rb",
     "lib/algorithms/string.rb",
     "lib/containers/deque.rb",
     "lib/containers/heap.rb",
     "lib/containers/kd_tree.rb",
     "lib/containers/priority_queue.rb",
     "lib/containers/queue.rb",
     "lib/containers/rb_tree_map.rb",
     "lib/containers/splay_tree_map.rb",
     "lib/containers/stack.rb",
     "lib/containers/suffix_array.rb",
     "lib/containers/trie.rb",
     "spec/bst_gc_mark_spec.rb",
     "spec/bst_spec.rb",
     "spec/deque_gc_mark_spec.rb",
     "spec/deque_spec.rb",
     "spec/heap_spec.rb",
     "spec/kd_expected_out.txt",
     "spec/kd_test_in.txt",
     "spec/kd_tree_spec.rb",
     "spec/map_gc_mark_spec.rb",
     "spec/priority_queue_spec.rb",
     "spec/queue_spec.rb",
     "spec/rb_tree_map_spec.rb",
     "spec/search_spec.rb",
     "spec/sort_spec.rb",
     "spec/splay_tree_map_spec.rb",
     "spec/stack_spec.rb",
     "spec/string_spec.rb",
     "spec/suffix_array_spec.rb",
     "spec/trie_spec.rb"
  ]
  s.homepage = %q{http://github.com/aunderwo/algorithms}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A library of algorithms and containers.}
  s.test_files = [
    "spec/rb_tree_map_spec.rb",
     "spec/kd_tree_spec.rb",
     "spec/suffix_array_spec.rb",
     "spec/trie_spec.rb",
     "spec/map_gc_mark_spec.rb",
     "spec/heap_spec.rb",
     "spec/stack_spec.rb",
     "spec/priority_queue_spec.rb",
     "spec/deque_gc_mark_spec.rb",
     "spec/bst_spec.rb",
     "spec/string_spec.rb",
     "spec/queue_spec.rb",
     "spec/deque_spec.rb",
     "spec/sort_spec.rb",
     "spec/bst_gc_mark_spec.rb",
     "spec/splay_tree_map_spec.rb",
     "spec/search_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

